resources:
- repo: self

pool:
  vmimage: 'ubuntu-16.04'

trigger:
- master

steps:
- script: |
    env
    pwd
    SCRIPTS=$(find . -type f -name \*\.sh | xargs)
    for SCRIPT in $SCRIPTS; do
      docker run --rm -v '$(Build.SourcesDirectory):/mnt' -t koalaman/shellcheck $SCRIPT
    done
