resources:
- repo: self

pool:
  vmimage: 'ubuntu-16.04'

trigger:
- master

steps:
- script: |
    env
    pwd
    find . -type f -name \*\.sh -exec docker run --rm -v '$(Build.SourcesDirectory):/mnt' -t koalaman/shellcheck {} \;
